### PR TITLE
Adding default implementations for some DataWriter methods

### PR DESCRIPTION
**Pull request by jglick**
Fixes incompatibilities from https://github.com/stapler/stapler/pull/61#issuecomment-190274458 & https://github.com/stapler/stapler/pull/106#discussion_r102306777, inspired by #128. Minor merge conflict expected with #127.

@reviewbybees

### CODE REVIEW

**Comment by batmat** [comment]
Seems like there was no PR build, shouldn't there be one?

**Comment by jglick** [comment]
There was no webhook set up for ci.jenkins.io @rtyler. As an org admin, I just added one, will see if it worked…

**Comment by jglick** [comment]
…and there we go!

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
