### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by vivek**
As requested by @oleg-nenashev and @daniel-beck for PR https://github.com/jenkinsci/jenkins/pull/2593#issuecomment-268729145.

### CODE REVIEW

**Comment by daniel-beck** [comment]
As I wrote in the other PR, it…

>  updates from 1.243 to 1.246, not from 1.244. Full list:
> 
> https://github.com/stapler/stapler/pull/73
> https://github.com/stapler/stapler/pull/75
> https://github.com/stapler/stapler/pull/77
> https://github.com/stapler/stapler/pull/78
> https://github.com/stapler/stapler/pull/79
> https://github.com/stapler/stapler/pull/80

Also, that merge introduced a regression which resulted in 1.247 and 1.248.

So whatever this PR does, it's not even close to a recent changelog.

**Comment by vivek** [comment]
@daniel-beck Added change logs from 1.243 till 1.248. Please take a look.

**Comment by oleg-nenashev** [comment]
I doubt the rendering is an expected one. It's hard to understand it

screen shot 2016-12-22 at 15 25 37

**Comment by vivek** [comment]
Go thru linked PRs and issues to get full understanding. This is summry it's unreasonable to expect to get full understanding of each or just from a sentence or two.

**Comment by oleg-nenashev** [comment]
I just say the layout is barely readable, I do not request more details in the changelog itself

**Comment by vivek** [comment]
@oleg-nenashev Made some adjustments, please take a look.

**Comment by oleg-nenashev** [comment]
LGTM 👍

**Comment by vivek** [comment]
@oleg-nenashev process wise, I wait for another LGTM or its good for merging? CI is failing but thats unrelated, this PR has no code changes.

**Comment by oleg-nenashev** [comment]
I think it's fine to merge since the current changelog provides valuable information. If there any additional fixes, we can add changes in follow-up PRs.

**Pull request merged**
