### PR TITLE
Inline Guava's `Iterators#limit`

### PR DESCRIPTION
**Pull request by basil**
A subset of #213 that is hopefully non-controversial and safe to land in the short term because it does not involve Caffeine or shading.

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Seems OK though I am unsure of the policy for inlining APL code into what is otherwise a BSD-2-Clause module. I would be inclined to just rewrite this one usage as I suspect that given the Javadoc any competent Java programmer could reimplement it (and we presumably do not even need all of it, like `remove` and `IllegalArgumentException`, just the very basic functionality).

**Comment by basil** [comment]
I really don't think this is an issue, but if someone wants to reimplement this then feel free.

**Comment by jglick** [comment]
FYI @jtnord

**Comment by timja** [comment]
As long as the license header is kept intact it would be ok I expect?

**Pull request merged**
